### ISSUE TITLE
NaN in simValues_atExpTime

### ISSUE THREAD

**Issue by Christoph27** [Open-Systems-Pharmacology/Matlab-Toolbox-Core#24]
In function "getPIWeightedResidualsForOSPSuiteExport.m":

Line:
simValues_atExpTime=interp1(sim_time,simValues,PI.output(iO).data_time);

If there are experimental values later than the last simulation time point, there is a NaN in the last element of "simValues_atExpTime". This gives a NaN in the residuals and in the total error at the end. 
I think the last NaN in "simValues_atExpTime" should just be discarded in such a case (there are legitimate situations to simulate shorter than all experimental data in a PI ;-).

**Comment by PavelBal** [comment]
afaik, PI in MoBi/PK-Sim always extends simulation time to the last observed point.
