### ISSUE TITLE
generateMatlabCodeForXML: error propagation

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/Matlab-Toolbox-Core#25]
**generateMatlabCodeForXML** does not properly show errors of underlying initSimulation
(e.g. in case invalid xml file was selected; Matlab path not properly set etc.).

Instead, the same error message is always shown: **_Error while setting the trees. Reference to non-existing field InputTab_**

This irritates users and makes debugging pretty hard. Instead, the real error must be shown.
(s. https://github.com/Open-Systems-Pharmacology/Matlab-Toolbox/issues/96 https://github.com/Open-Systems-Pharmacology/Matlab-Toolbox/issues/93 )

![grafik](https://user-images.githubusercontent.com/25061876/53091480-53048780-3512-11e9-9565-9da0c6978d34.png)

**Comment by msevestre** [comment]
YES PLEASE!!!
